# Generated by Django 5.2.1 on 2025-09-30 21:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0004_arac_satildi_mi'),
    ]

    operations = [
        migrations.AddField(
            model_name='arac',
            name='ilan_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arac',
            name='satis_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
