# Generated by Django 5.2.1 on 2025-11-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0006_remove_arac_fotoğraf_alter_arac_id_ilandosyalari'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arac',
            old_name='fiyat',
            new_name='ilan_fiyat',
        ),
        migrations.AddField(
            model_name='arac',
            name='alis_fiyat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arac',
            name='kar_zarar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arac',
            name='satis_fiyat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
