# Generated by Django 5.2.1 on 2026-01-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0010_replace_marka_model_with_foreignkeys'),
    ]

    operations = [
        migrations.CreateModel(
            name='personel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ad', models.CharField(max_length=100)),
                ('soyad', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=20)),
                ('e_posta', models.EmailField(max_length=254)),
            ],
        ),
    ]
