# Generated by Django 5.2.1 on 2026-01-05 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0011_personel'),
    ]

    operations = [
        migrations.AddField(
            model_name='arac',
            name='personel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='araclar', to='galeri.personel'),
        ),
    ]
