# Generated by Django 5.2.1 on 2026-01-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0012_arac_personel'),
    ]

    operations = [
        migrations.AddField(
            model_name='arac',
            name='kilometre',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arac',
            name='motor_gucu',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arac',
            name='vites_tipi',
            field=models.CharField(blank=True, choices=[('manuel', 'Manuel'), ('otomatik', 'Otomatik')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='arac',
            name='yakit_tipi',
            field=models.CharField(blank=True, choices=[('benzin', 'Benzin'), ('dizel', 'Dizel'), ('elektrik', 'Elektrik')], max_length=100, null=True),
        ),
    ]
