# Generated by Django 5.2.1 on 2026-01-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0013_arac_kilometre_arac_motor_gucu_arac_vites_tipi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arac',
            name='kilometre',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='arac',
            name='motor_gucu',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
