# Generated by Django 5.2.1 on 2026-01-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0014_alter_arac_kilometre_alter_arac_motor_gucu'),
    ]

    operations = [
        migrations.AddField(
            model_name='arac',
            name='motor_hacmi',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
