# Generated by Django 5.2.1 on 2026-01-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0015_arac_motor_hacmi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arac',
            name='motor_hacmi',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=10, null=True),
        ),
    ]
