# Generated by Django 5.0.7 on 2025-01-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('yil', models.IntegerField()),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aciklama', models.TextField()),
            ],
        ),
    ]
