# Generated by Django 5.0.7 on 2025-01-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arac',
            name='fotoğraf',
            field=models.ImageField(default=1, upload_to='araclar/'),
            preserve_default=False,
        ),
    ]
