# Generated by Django 5.2.1 on 2025-09-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0002_arac_fotoğraf'),
    ]

    operations = [
        migrations.AddField(
            model_name='arac',
            name='durum',
            field=models.CharField(choices=[('yeni', 'Yeni'), ('firsat', 'Fırsat')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arac',
            name='fiyat',
            field=models.IntegerField(),
        ),
    ]
