# Generated by Django 5.2.1 on 2025-09-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0003_arac_durum_alter_arac_fiyat'),
    ]

    operations = [
        migrations.AddField(
            model_name='arac',
            name='satildi_mi',
            field=models.BooleanField(default=False),
        ),
    ]
