# Generated by Django 5.2.1 on 2025-09-30 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0005_arac_ilan_tarihi_arac_satis_tarihi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arac',
            name='fotoğraf',
        ),
        migrations.AlterField(
            model_name='arac',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ilanDosyalari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotoğraf', models.ImageField(upload_to='araclar/')),
                ('sıra', models.PositiveIntegerField(default=1, help_text='Fotoğraf sırası')),
                ('ana_fotoğraf', models.BooleanField(default=False, help_text='Ana fotoğraf olarak işaretle')),
                ('yükleme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('aracid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotograflar', to='galeri.arac')),
            ],
            options={
                'verbose_name': 'Araç Fotoğrafı',
                'verbose_name_plural': 'Araç Fotoğrafları',
                'ordering': ['sıra', 'yükleme_tarihi'],
            },
        ),
    ]
